version: "3.9"
    
services:
  db:
    image: mysql:8.0.25
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
     - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mudar@123
      MYSQL_DATABASE: livraria_test
      MYSQL_USER: livraria
      MYSQL_PASSWORD: mudar@123

volumes:
  db_data: {}